console.log(localStorage.getItem('name'));
$.ajax({
  type:"POST",
  url:"process.njs",
  data:{
    user:localStorage.getItem('name'),
  },
  success:function(receive_data){
    console.log(receive_data);
    localStorage.setItem('user_money',receive_data);
  },
  error:function(){
    console.log('err');
  },
});
