$('#create').click(function(){
  $.ajax({
    type:"POST",
    url:'signup.njs',
    data:{username:$('input[name="username"]').val(),
          pwd:$('input[name="pwd"]').val(),
          email:$('input[name="email"]').val(),
          year:$('#year').val(),
          month:$('#month').val(),
          day:$('#day').val(),
          bank:$('input[name="bank_name"]').val(),
          bankcode:$('input[name="bank_code"]').val(),
          card:$('input[name="debit_card"]').val()
          
          },
    success:function(response){
      if($('input[name="pwd"]').val()==$('input[name="checkpwd"]').val()){
        localStorage.setItem('key',$('input[name="username"]').val());
        window.location.href="http://luffy.ee.ncku.edu.tw/~poyushen/profile";
      }
      else{
        alert('請再次確認密碼');
      }
    },
    error:function(){
      console.log('err');
    }
  });
});
